site_name: Restaurant API Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Services:
    - Overview: services/overview.md
    - User Service: services/user-service.md
    - Table Service: services/table-service.md
    - Menu Service: services/menu-service.md
    - Order Service: services/order-service.md
    - Kitchen Service: services/kitchen-service.md
    - Payment Service: services/payment-service.md
  - Database Schema: database-schema.md
  - Development Guide: development-guide.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
